name: Create Diagram

on:
    push:
        branches:
            - main

jobs:
    create-diagram:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.1
            - name: Generate diagram
              uses: githubocto/repo-visualizer@0.9.1
